name: "Default Checks"

permissions: 
  checks: read
  statuses: read
  contents: read

on:
  pull_request:
    branches:
      - main

jobs:
  check:
    uses: rstuhlmuller/workflows/.github/workflows/default.yml@main