name: Terragrunt Plan
run-name: Terragrunt Plan - PR/${{ github.event.pull_request.number }}

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
    branches:
      - main

permissions:
  checks: write
  statuses: write
  contents: read

jobs:
  terragrunt-plan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory:
          - "rstuhlmuller/github"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Terragrunt and OpenTofu
        uses: gruntwork-io/terragrunt-action@v3
        with:
          tofu_version: "1.10.6"
          tg_version: "0.84.1"

      - name: Terragrunt Plan
        working-directory: ${{ matrix.directory }}
        run: |
          terragrunt plan
